/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Sneaker } from "./Sneaker";
import { SneakerCountArgs } from "./SneakerCountArgs";
import { SneakerFindManyArgs } from "./SneakerFindManyArgs";
import { SneakerFindUniqueArgs } from "./SneakerFindUniqueArgs";
import { CreateSneakerArgs } from "./CreateSneakerArgs";
import { UpdateSneakerArgs } from "./UpdateSneakerArgs";
import { DeleteSneakerArgs } from "./DeleteSneakerArgs";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { SneakerService } from "../sneaker.service";
@graphql.Resolver(() => Sneaker)
export class SneakerResolverBase {
  constructor(protected readonly service: SneakerService) {}

  async _sneakersMeta(
    @graphql.Args() args: SneakerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Sneaker])
  async sneakers(
    @graphql.Args() args: SneakerFindManyArgs
  ): Promise<Sneaker[]> {
    return this.service.sneakers(args);
  }

  @graphql.Query(() => Sneaker, { nullable: true })
  async sneaker(
    @graphql.Args() args: SneakerFindUniqueArgs
  ): Promise<Sneaker | null> {
    const result = await this.service.sneaker(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Sneaker)
  async createSneaker(
    @graphql.Args() args: CreateSneakerArgs
  ): Promise<Sneaker> {
    return await this.service.createSneaker({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Sneaker)
  async updateSneaker(
    @graphql.Args() args: UpdateSneakerArgs
  ): Promise<Sneaker | null> {
    try {
      return await this.service.updateSneaker({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sneaker)
  async deleteSneaker(
    @graphql.Args() args: DeleteSneakerArgs
  ): Promise<Sneaker | null> {
    try {
      return await this.service.deleteSneaker(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Order], { name: "orders" })
  async findOrders(
    @graphql.Parent() parent: Sneaker,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findOrders(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
