/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SneakerService } from "../sneaker.service";
import { SneakerCreateInput } from "./SneakerCreateInput";
import { Sneaker } from "./Sneaker";
import { SneakerFindManyArgs } from "./SneakerFindManyArgs";
import { SneakerWhereUniqueInput } from "./SneakerWhereUniqueInput";
import { SneakerUpdateInput } from "./SneakerUpdateInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";

export class SneakerControllerBase {
  constructor(protected readonly service: SneakerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sneaker })
  async createSneaker(
    @common.Body() data: SneakerCreateInput
  ): Promise<Sneaker> {
    return await this.service.createSneaker({
      data: data,
      select: {
        color: true,
        createdAt: true,
        description: true,
        id: true,
        image: true,
        name: true,
        price: true,
        size: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Sneaker] })
  @ApiNestedQuery(SneakerFindManyArgs)
  async sneakers(@common.Req() request: Request): Promise<Sneaker[]> {
    const args = plainToClass(SneakerFindManyArgs, request.query);
    return this.service.sneakers({
      ...args,
      select: {
        color: true,
        createdAt: true,
        description: true,
        id: true,
        image: true,
        name: true,
        price: true,
        size: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sneaker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async sneaker(
    @common.Param() params: SneakerWhereUniqueInput
  ): Promise<Sneaker | null> {
    const result = await this.service.sneaker({
      where: params,
      select: {
        color: true,
        createdAt: true,
        description: true,
        id: true,
        image: true,
        name: true,
        price: true,
        size: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sneaker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSneaker(
    @common.Param() params: SneakerWhereUniqueInput,
    @common.Body() data: SneakerUpdateInput
  ): Promise<Sneaker | null> {
    try {
      return await this.service.updateSneaker({
        where: params,
        data: data,
        select: {
          color: true,
          createdAt: true,
          description: true,
          id: true,
          image: true,
          name: true,
          price: true,
          size: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sneaker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSneaker(
    @common.Param() params: SneakerWhereUniqueInput
  ): Promise<Sneaker | null> {
    try {
      return await this.service.deleteSneaker({
        where: params,
        select: {
          color: true,
          createdAt: true,
          description: true,
          id: true,
          image: true,
          name: true,
          price: true,
          size: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: SneakerWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        orderDate: true,
        quantity: true,

        sneaker: {
          select: {
            id: true,
          },
        },

        totalPrice: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  async connectOrders(
    @common.Param() params: SneakerWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateSneaker({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  async updateOrders(
    @common.Param() params: SneakerWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateSneaker({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  async disconnectOrders(
    @common.Param() params: SneakerWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateSneaker({
      where: params,
      data,
      select: { id: true },
    });
  }
}
